Pull Request for the 2nd Project of the Javascript Module
jose-Abel/restaurantPage pull request #1
Opened 2021-05-23 17:48 UTC by jose-Abel

Hello,

This is my request for a Pull Review for the 2nd project in the Javascript modules that consist of creating a multi page websites with Javascript and webpack where all the HTML elements had to be created with Javascript. 

Hoping to get an amazing feedback!

2021-05-24 00:59 UTC, bellom requested changes
## Hi @jose-Abel  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a 1 issue left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_*

2021-05-24 00:59 UTC, bellom commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
We should have all necessarily used packages that should be included in `package.json` like `webpack`, `webpack-cli`, `webpack-dev-server` etc. Also, those packages should be added as **devDependencies** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/devdep_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))

We also need inform users about these script in the README file. This information can be placed in the Usage section. This way users can know the command to run to start your application.

2021-05-25 04:15 UTC, rindrajosia approved these changes
Approved! :tada:

Congratulations are in order!! :clap: Keep up the good work!

- [ ] [OPTIONAL] Keep all the styling logic in CSS files (If you need to change something like a background image, add the classes with the different backgrounds to the CSS and then change the class name attribute with JavaScript) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/styling_requirement.png) from Pathwright)
- [ ] [OPTIONAL] Please check your live demo because the `navbar` doesn't work.

All the best on your next projects! :wink:
Rindra Josia

2021-05-25 04:15 UTC, rindrajosia commented on src/contact.js
> +  h1.style.fontSize = '5rem';
Keep all the styling logic in CSS files

2021-05-25 04:15 UTC, rindrajosia commented on src/divBox.js
> +  div1.style.border = '5px solid #fceabb';
Keep all the styling logic in CSS files

2021-05-25 04:15 UTC, rindrajosia commented on src/divBox.js
> +    imageElement.style.borderRadius = '20%';
Keep all the styling logic in CSS files

2021-05-25 04:15 UTC, rindrajosia commented on src/divBox.js
> +    h3Element.style.fontSize = '2rem';
Keep all the styling logic in CSS files

2021-05-25 04:15 UTC, rindrajosia commented on src/divBox.js
> +  span2.style.marginLeft = '1.5rem';
Keep all the styling logic in CSS files

2021-05-25 04:15 UTC, rindrajosia commented on src/home.js
> +  imagesArray[1].style.borderRadius = '20%';
Keep all the styling logic in CSS files

2021-05-25 04:15 UTC, rindrajosia commented on src/menu.js
> +  secondH2.style.fontSize = '3.5rem';
Keep all the styling logic in CSS files

2021-05-25 04:15 UTC, rindrajosia commented on src/menu.js
> +    imagesArray[i].style.order = 1;
Keep all the styling logic in CSS files

2021-05-25 04:15 UTC, rindrajosia commented on src/navbar.js
> +    liArray[i].style.color = '#fceabb';
Keep all the styling logic in CSS files

2021-05-25 04:15 UTC, rindrajosia commented on src/navbar.js
> +    aArray[i].style.cursor = 'pointer';
Keep all the styling logic in CSS files

2021-05-25 04:15 UTC, rindrajosia commented on src/navbar.js
> +  ul.style.justifyContent = 'center';
Keep all the styling logic in CSS files

2021-05-25 15:42 UTC, merged